apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app
  namespace: test-namespace
  labels:
    appName: "testApp"
    env: "test"
    manifestVersion: "0.0.1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-app
  namespace: test-namespace
  labels:
    appName: "testApp"
    env: "test"
    manifestVersion: "0.0.1"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-app-role
  namespace: test-namespace
  labels:
    appName: "testApp"
    env: "test"
    manifestVersion: "0.0.1"
subjects:
  - kind: ServiceAccount
    name: test-app
    namespace: test-namespace
roleRef:
  kind: Role
  name: test-app-role
  apiGroup: rbac.authorization.k8s.io